import type { ComponentApi } from '../../catalog/types.js';

export const IconComponentSchema: ComponentApi = {
  name: 'Icon',
  description: '图标组件，支持内置图标名称或自定义 SVG 路径',
  schema: {
    type: 'object',
    properties: {
      component: { const: 'Icon' },
      name: {
        description: '图标名称或 SVG 路径',
        oneOf: [
          {
            type: 'string',
            enum: [
              'accountCircle',
              'add',
              'arrowBack',
              'arrowForward',
              'attachFile',
              'calendarToday',
              'call',
              'camera',
              'check',
              'close',
              'delete',
              'download',
              'edit',
              'event',
              'error',
              'fastForward',
              'favorite',
              'favoriteOff',
              'folder',
              'help',
              'home',
              'info',
              'locationOn',
              'lock',
              'lockOpen',
              'mail',
              'menu',
              'moreVert',
              'moreHoriz',
              'notificationsOff',
              'notifications',
              'pause',
              'payment',
              'person',
              'phone',
              'photo',
              'play',
              'print',
              'refresh',
              'rewind',
              'search',
              'send',
              'settings',
              'share',
              'shoppingCart',
              'skipNext',
              'skipPrevious',
              'star',
              'starHalf',
              'starOff',
              'stop',
              'upload',
              'visibility',
              'visibilityOff',
              'volumeDown',
              'volumeMute',
              'volumeOff',
              'volumeUp',
              'warning',
            ],
          },
          {
            type: 'object',
            properties: { svgPath: { $ref: 'common_types.json#/$defs/DynamicString' } },
            required: ['svgPath'],
            additionalProperties: false,
          },
          { $ref: 'common_types.json#/$defs/DataBinding' },
        ],
      },
      weight: {
        type: 'number',
        description: '组件在布局中的权重值',
      },
    },
    required: ['component', 'name'],
  },
};
