/**
 * A2UI v1.0 Schema 统一导出
 */

// 常量
export {
  SPEC_VERSION,
  SPEC_BASE_URL,
  A2UI_MIME_TYPE,
  SUPPORTED_VERSIONS,
  MessageType,
  CatalogKeys,
  SurfaceKeys,
  ROOT_ID,
  MAX_GLOBAL_DEPTH,
  MAX_FUNC_CALL_DEPTH,
} from './constants.js';

// 公共类型
export {
  ComponentIdSchema,
  CallIdSchema,
  AccessibilityAttributesSchema,
  ComponentCommonSchema,
  DataBindingSchema,
  FunctionCallSchema,
  IndexSystemFunctionSchema,
  DynamicValueSchema,
  DynamicStringSchema,
  DynamicNumberSchema,
  DynamicBooleanSchema,
  DynamicStringListSchema,
  TemplateChildListSchema,
  ChildListSchema,
  SingleReferenceSchema,
  ListReferenceSchema,
  CheckRuleSchema,
  CheckableSchema,
  ValidationResultSchema,
  ActionEventSchema,
  ActionSchema,
  FunctionResponseSchema,
  type ComponentId,
  type CallId,
  type AccessibilityAttributes,
  type ComponentCommon,
  type DataBinding,
  type FunctionCall,
  type IndexSystemFunction,
  type DynamicValue,
  type DynamicString,
  type DynamicNumber,
  type DynamicBoolean,
  type DynamicStringList,
  type TemplateChildList,
  type ChildList,
  type SingleReference,
  type ListReference,
  type CheckRule,
  type Checkable,
  type ValidationResult,
  type ActionEvent,
  type Action,
  type FunctionResponse,
  isDataBinding,
  isFunctionCall,
  isTemplateChildList,
} from './common-types.js';

// Agent 到 Renderer 消息
export {
  ComponentPayloadSchema,
  ComponentsListSchema,
  CreateSurfacePayloadSchema,
  CreateSurfaceMessageSchema,
  UpdateComponentsPayloadSchema,
  UpdateComponentsMessageSchema,
  UpdateDataModelPayloadSchema,
  UpdateDataModelMessageSchema,
  DeleteSurfacePayloadSchema,
  DeleteSurfaceMessageSchema,
  CallRendererFunctionPayloadSchema,
  CallRendererFunctionMessageSchema,
  AgentFunctionResponsePayloadSchema,
  AgentFunctionResponseMessageSchema,
  A2uiMessageSchema,
  A2uiMessageListSchema,
  A2uiMessageListWrapperSchema,
  type ComponentPayload,
  type ComponentsList,
  type CreateSurfacePayload,
  type CreateSurfaceMessage,
  type UpdateComponentsPayload,
  type UpdateComponentsMessage,
  type UpdateDataModelPayload,
  type UpdateDataModelMessage,
  type DeleteSurfacePayload,
  type DeleteSurfaceMessage,
  type CallRendererFunctionPayload,
  type CallRendererFunctionMessage,
  type AgentFunctionResponsePayload,
  type AgentFunctionResponseMessage,
  type A2uiMessage,
  type A2uiMessageList,
  type A2uiMessageListWrapper,
  isCreateSurfaceMessage,
  isUpdateComponentsMessage,
  isUpdateDataModelMessage,
  isDeleteSurfaceMessage,
  isCallRendererFunctionMessage,
  isAgentFunctionResponseMessage,
} from './agent-to-renderer.js';

// Renderer 到 Agent 消息
export {
  ClientActionPayloadSchema,
  A2uiClientActionMessageSchema,
  CallAgentFunctionPayloadSchema,
  A2uiClientCallAgentFunctionMessageSchema,
  RendererFunctionResponsePayloadSchema,
  A2uiRendererFunctionResponseMessageSchema,
  ValidationFailedErrorSchema,
  GenericErrorSchema,
  ClientErrorPayloadSchema,
  A2uiClientErrorMessageSchema,
  A2uiClientMessageSchema,
  A2uiClientMessageListSchema,
  A2uiClientMessageListWrapperSchema,
  type ClientActionPayload,
  type A2uiClientActionMessage,
  type CallAgentFunctionPayload,
  type A2uiClientCallAgentFunctionMessage,
  type RendererFunctionResponsePayload,
  type A2uiRendererFunctionResponseMessage,
  type ValidationFailedError,
  type GenericError,
  type ClientErrorPayload,
  type A2uiClientErrorMessage,
  type A2uiClientMessage,
  type A2uiClientMessageList,
  type A2uiClientMessageListWrapper,
  isClientActionMessage,
  isCallAgentFunctionMessage,
  isRendererFunctionResponseMessage,
  isClientErrorMessage,
  isValidationFailedError,
} from './renderer-to-agent.js';

// Renderer 能力
export {
  FunctionDefinitionSchema,
  InlineCatalogSchema,
  V10CapabilitiesSchema,
  A2uiClientCapabilitiesSchema,
  type FunctionDefinition,
  type InlineCatalog,
  type V10Capabilities,
  type A2uiClientCapabilities,
  getV10Capabilities,
} from './renderer-capabilities.js';

// Agent 能力
export {
  V10ServerCapabilitiesSchema,
  A2uiServerCapabilitiesSchema,
  type V10ServerCapabilities,
  type A2uiServerCapabilities,
  getV10ServerCapabilities,
} from './agent-capabilities.js';

// 组合约束校验（Surface 容器 + allowedParents/allowedChildren）
export {
  SURFACE_COMPONENT,
  UNALLOWED_PARENT,
  UNALLOWED_CHILD,
  extractParentChildPairs,
  checkCompositionConstraints,
  type CompositionConstraints,
  type CompositionConstraintResolver,
} from './composition-checker.js';
